name: PHP Composer

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    name: "PHP ${{ matrix.php }}"
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      matrix:
        php: [ '8.2', '8.3' ]

    steps:
    - uses: actions/checkout@v3
    - name: "Set up php"
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "${{ matrix.php }}"
        coverage: "none"

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: vendor/bin/phpstan

    - name: Run codestyle
      run: vendor/bin/php-cs-fixer check src
